### ISSUE TITLE
Sprint Adjuster: Sprinting causes active class skill to deactivate

### ISSUE THREAD

**Issue by KNGN** [plu5/p-borderlands#1]
using the mod blocked my salvador skills from working at all

**Comment by plu5** [comment]
Can you give me more details?

1. Which mod?
2. Can you give me steps to reproduce the problem?

Also check the console log or `python-sdk.log` in `Binaries/Win32` after the problem occurs. You can copy the output and upload to www.pastebin.com.

**Comment by KNGN** [comment]
i used the sprint adjuster mod. what i did was to set sprint to 0, i've also located python-sdk.log fiel but i dont know what i'm looking for.

**Comment by plu5** [comment]
Bug confirmed. Sprinting with the mod toggled on causes any class skill to deactivate. This is probably because I am doing `ApplyCharacterClassDefaults` to apply the speed. I’ll look into how to apply it in a different way.

Temporary (non-ideal) workaround is to use the keybinding (<kbd>Ctrl</kbd> by default) to toggle it off when using class skills.

I’ll try to fix this ASAP! Thanks again for bringing it to my attention.

**Comment by plu5** [comment]
Should be fixed in Sprint Adjuster 1.1.0, please update your mod!

[Link to latest release](https://github.com/plu5/p-borderlands/releases/latest)
