### ISSUE TITLE
Sprint Adjuster: Sprinting causes Badass points to not apply

### ISSUE THREAD

**Issue by SporgWaffle** [plu5/p-borderlands#2]
Sprinting disables badass point application until they are toggled off and back on again. They are disabled again after sprinting again.

**Comment by plu5** [comment]
Thank you for the report! I expect this is an issue caused by me doing `ApplyCharacterClassDefaults ` to apply the speed, which caused issue #1. I changed the approach in version 1.1.0 to change an attribute in `GD_PlayerShared.Sprint.SprintDefinition_Default` instead to apply the speed. Can you check whether this is also fixed?

[Link to latest release](https://github.com/plu5/p-borderlands/releases/latest)

**Comment by SporgWaffle** [comment]
Works perfectly!
