### ISSUE TITLE
Sprint Adjuster: Gaige Anarchy don't work which this mod.

### ISSUE THREAD

**Issue by yarrg** [plu5/p-borderlands#3]
When Sprint Adjuster enable Anarchy Stacks don't display and don't add.

**Comment by plu5** [comment]
Thanks for the report! I believe this is the old bug (#1, #2) that was fixed in the [latest version](https://github.com/plu5/p-borderlands/releases/tag/v1.1.1). I tested it just now and I am getting Anarchy stacks normally. Let me know if you are still having this problem on the latest version + steps to reproduce what you’re seeing.
