### ISSUE TITLE
Breaks Zer0's execute skill

### ISSUE THREAD

**Issue by ericgryffindor** [plu5/p-borderlands#4]
when using the mod execute will not cast

**Comment by plu5** [comment]
Are you sure you are using the latest version of the mod? I believe this is the old bug (#1, #2, #3) that was fixed in the [latest version](https://github.com/plu5/p-borderlands/releases/latest). I tested it just now and cannot replicate the issue on latest. Let me know if you are still having this problem on the latest version + steps to reproduce what you’re seeing.
