### ISSUE TITLE
Mod disables some of Maya skills and amps Shields 

### ISSUE THREAD

**Issue by GymLeaderNick1892** [plu5/p-borderlands#7]
when the mod is activated and after you have sprinted. Amp Shields stop working unless you drop it and repick it up. it will break when you sprint again. Maya's Skills: Ruin, Helios, and Cloudkill don't trigger. Phaselocking only phas locks. Cloudkill's green cloud doesn't appear when shoot an enemy

**Comment by plu5** [comment]
Where did you get the mod from, and are you using the [latest version](https://github.com/plu5/p-borderlands/releases/latest)? It sounds like an old issue (https://github.com/plu5/p-borderlands/issues/1) that was fixed in 1.1.0. Changing speed is now done by just modifying the Sprint Definition so it should not be affecting anything else.

**Comment by GymLeaderNick1892** [comment]
yeah i think i had a previous version somehow i got it from here https://bl-sdk.github.io/mods/SprintAdjuster/

**Comment by GymLeaderNick1892** [comment]
i just downloaded it again and everything works

**Comment by plu5** [comment]
Thanks for the confirmation. Strange that you didn’t get the latest version when following the link from there. If you check the closed issues, you are not the only person this has happened to. I wonder if this is because you went on the page for [ExpAdjuster](https://bl-sdk.github.io/mods/ExpAdjuster/) or [SavesBackuper](https://bl-sdk.github.io/mods/SavesBackuper/) and clicked the download link from there? Because I have all my mods on the same repo and they all have different versions, they link to a release that has the latest version for them but an earlier version of SprintAdjuster. I now updated all of them to link to latest release so hopefully this won’t happen to other people if this is indeed what happened. The site should update in about an hour.
